const ACTION_TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  GET_DETAIL_USER: 'GET_DETAIL_USER',
  GET_DETAIL_USER_SUCCESS: 'GET_DETAIL_USER_SECCESS',
  GET_DETAIL_USER_FAILED: 'GET_DETAIL_USER_FAILED',
  REMOVE_USER: 'REMOVE_USER',
  REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_USER_FAILED: 'REMOVE_USER_FAILED'
};

export default ACTION_TYPES;
